In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [8]:
data = pd.read_csv("Salary_dt.csv")
data.head()

company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [9]:
ind_var = data.drop("salary_more_then_100k", axis=1)
tar_var = data.salary_more_then_100k

In [4]:
from sklearn.preprocessing import LabelEncoder

In [10]:
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

In [11]:
ind_var["company_le"] = le_company.fit_transform(ind_var["company"])
ind_var["job_le"] = le_job.fit_transform(ind_var["job"])
ind_var["degree_le"] = le_degree.fit_transform(ind_var["degree"])
ind_var.head()

company                  job     degree  company_le  job_le  degree_le
0  google      sales executive  bachelors           2       2          0
1  google      sales executive    masters           2       2          1
2  google     business manager  bachelors           2       0          0
3  google     business manager    masters           2       0          1
4  google  computer programmer  bachelors           2       1          0

In [12]:
ind_var_num = ind_var.drop(["company","job","degree"], axis=1)
ind_var_num

company_le  job_le  degree_le
0            2       2          0
1            2       2          1
2            2       0          0
3            2       0          1
4            2       1          0
5            2       1          1
6            0       2          1
7            0       1          0
8            0       0          0
9            0       0          1
10           1       2          0
11           1       2          1
12           1       0          0
13           1       0          1
14           1       1          0
15           1       1          1

# Training Model

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(ind_var_num,tar_var, test_size = 0.20)

In [16]:
from sklearn.tree import DecisionTreeClassifier

In [17]:
model = DecisionTreeClassifier()

In [18]:
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [19]:
y_pred = model.predict(X_test)
y_pred

array([1, 1, 1, 0], dtype=int64)

In [23]:
model.score(X_test, y_test)*100

75.0

In [25]:
model.predict([[2,2,1]])

C:\Users\Ankit\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

# Using Dummy Variables

In [33]:
ind_var = data.drop("salary_more_then_100k", axis=1)
tar_var = data.salary_more_then_100k

In [34]:
ind_var

company                  job     degree
0       google      sales executive  bachelors
1       google      sales executive    masters
2       google     business manager  bachelors
3       google     business manager    masters
4       google  computer programmer  bachelors
5       google  computer programmer    masters
6   abc pharma      sales executive    masters
7   abc pharma  computer programmer  bachelors
8   abc pharma     business manager  bachelors
9   abc pharma     business manager    masters
10    facebook      sales executive  bachelors
11    facebook      sales executive    masters
12    facebook     business manager  bachelors
13    facebook     business manager    masters
14    facebook  computer programmer  bachelors
15    facebook  computer programmer    masters

In [43]:
ind_var_com_dummies = pd.get_dummies(ind_var.company, prefix ="company", drop_first = True)
ind_var_job_dummies = pd.get_dummies(ind_var.job, prefix ="company", drop_first = True)
ind_var_degree_dummies = pd.get_dummies(ind_var.degree, prefix ="company")

In [66]:
new_df = pd.concat([ind_var,ind_var_com_dummies,ind_var_job_dummies,ind_var_degree_dummies], axis=1)
new_df

company                  job     degree  company_facebook  \
0       google      sales executive  bachelors                 0   
1       google      sales executive    masters                 0   
2       google     business manager  bachelors                 0   
3       google     business manager    masters                 0   
4       google  computer programmer  bachelors                 0   
5       google  computer programmer    masters                 0   
6   abc pharma      sales executive    masters                 0   
7   abc pharma  computer programmer  bachelors                 0   
8   abc pharma     business manager  bachelors                 0   
9   abc pharma     business manager    masters                 0   
10    facebook      sales executive  bachelors                 1   
11    facebook      sales executive    masters                 1   
12    facebook     business manager  bachelors                 1   
13    facebook     business manager    masters                 1   
14    facebook  computer programmer  bachelors                 1   
15    facebook  computer programmer    masters                 1   

    company_google  company_computer programmer  company_sales executive  \
0                1                            0                        1   
1                1                            0                        1   
2                1                            0                        0   
3                1                            0                        0   
4                1                            1                        0   
5                1                            1                        0   
6                0                            0                        1   
7                0                            1                        0   
8                0                            0                        0   
9                0                            0                        0   
10               0                            0                        1   
11               0                            0                        1   
12               0                            0                        0   
13               0                            0                        0   
14               0                            1                        0   
15               0                            1                        0   

    company_bachelors  company_masters  
0                   1                0  
1                   0                1  
2                   1                0  
3                   0                1  
4                   1                0  
5                   0                1  
6                   0                1  
7                   1                0  
8                   1                0  
9                   0                1  
10                  1                0  
11                  0                1  
12                  1                0  
13                  0                1  
14                  1                0  
15                  0                1

In [67]:
final = new_df.drop(["company", "job","degree"], axis=1)
final

company_facebook  company_google  company_computer programmer  \
0                  0               1                            0   
1                  0               1                            0   
2                  0               1                            0   
3                  0               1                            0   
4                  0               1                            1   
5                  0               1                            1   
6                  0               0                            0   
7                  0               0                            1   
8                  0               0                            0   
9                  0               0                            0   
10                 1               0                            0   
11                 1               0                            0   
12                 1               0                            0   
13                 1               0                            0   
14                 1               0                            1   
15                 1               0                            1   

    company_sales executive  company_bachelors  company_masters  
0                         1                  1                0  
1                         1                  0                1  
2                         0                  1                0  
3                         0                  0                1  
4                         0                  1                0  
5                         0                  0                1  
6                         1                  0                1  
7                         0                  1                0  
8                         0                  1                0  
9                         0                  0                1  
10                        1                  1                0  
11                        1                  0                1  
12                        0                  1                0  
13                        0                  0                1  
14                        0                  1                0  
15                        0                  0                1

In [88]:
X_train, X_test, y_train, y_test = train_test_split(final,tar_var, test_size = 0.30)

In [76]:
model2 = DecisionTreeClassifier()
model2.fit(X_train, y_train)

DecisionTreeClassifier()

In [89]:
y_pred = model2.predict(X_test)
y_pred

array([1, 0, 1, 0, 1], dtype=int64)

In [90]:
y_test

6     0
4     0
14    1
8     0
10    1
Name: salary_more_then_100k, dtype: int64

In [91]:
model2.score(X_test, y_test)*100

80.0

# Exercise

In [92]:
df = pd.read_csv("Titanic_dt.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [93]:
df_new = df.drop(["PassengerId","Name","SibSp","Parch","Ticket","Cabin","Embarked"], axis = 1)
df_new.head()

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [94]:
df_new.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
Fare          0
dtype: int64

In [98]:
df_new["Age"].fillna(df_new.Age.mean(), inplace = True)

In [99]:
df_new.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
Fare        0
dtype: int64

In [102]:
df_new["Sex"] = df_new.Sex.map({"male": 1, "female": 0})

In [103]:
df_new.head()

Survived  Pclass  Sex   Age     Fare
0         0       3    1  22.0   7.2500
1         1       1    0  38.0  71.2833
2         1       3    0  26.0   7.9250
3         1       1    0  35.0  53.1000
4         0       3    1  35.0   8.0500

In [106]:
X = df_new.drop('Survived', axis=1)
y = df_new["Survived"]

In [107]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.30)

In [108]:
from sklearn import tree
model3 = tree.DecisionTreeClassifier()

In [109]:
model3.fit(X_train, y_train)

DecisionTreeClassifier()

In [110]:
y_pred3 = model3.predict(X_test)

In [111]:
model3.score(X_test, y_test)*100

81.71641791044776